<?php
/**
 * @project  Investment Deals
 * @copyright © 2017 by ivoglent
 * @author ivoglent
 * @time  9/7/17.
 */


namespace ivoglent\media\manager\controllers;


use ivoglent\media\manager\models\Media;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\UnauthorizedHttpException;

class ManagerController extends Controller
{
    /**
     * @param \yii\base\Action $action
     * @return bool
     * @throws UnauthorizedHttpException
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest){
            throw new UnauthorizedHttpException("Reuquired logged in user");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionDialog()
    {
        $user = \Yii::$app->user->identity;
        $dataProvider = new ActiveDataProvider([
            'query' => Media::find()->where(['created_by' => $user->getId()])
        ]);
        return $this->renderPartial('dialog', [
            'dataProvider' => $dataProvider
        ]);
    }
}