<?php
/**
 * @project  Investment Deals
 * @copyright © 2017 by ivoglent
 * @author ivoglent
 * @time  9/7/17.
 */


namespace ivoglent\media\manager;

use yii\base\InvalidConfigException;

class Module extends \yii\base\Module
{
    public $controllerNamespace         = 'ivoglent\media\manager\controllers';
    public $userClass                   = 'common\models\User';

    public $uploadDir                   = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->uploadDir)) {
            throw new InvalidConfigException("Missing uploadDir config for media manager");
        }
        $this->userClass = \Yii::$app->user->identityClass;
    }
}