<?php
/**
 * @project  Investment Deals
 * @copyright © 2017 by ivoglent
 * @author ivoglent
 * @time  9/7/17.
 */


namespace ivoglent\media\manager;


use yii\helpers\BaseUrl;
use yii\web\View;

class Widget extends \yii\base\Widget
{
    /**
     * Asset URL after published to web/assets folder
     * @var string
     */
    private $assetUrl = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->assetUrl = $this->releaseAssets();
        $options = [
            'baseUrl' => BaseUrl::base(true)
        ];
        $this->view->registerJs('window.mediaOptions = ' . json_encode($options) . ';', View::POS_HEAD);
    }

    /**
     * Register asset bundle to Yii view
     * @param $files
     */
    protected function registerAssets($files)
    {
        foreach ($files as $type => $_files) {
            if ($type == 'script') {
                foreach ($_files as $file) {
                    $this->view->registerJsFile($this->assetUrl . $file);
                }
            } else {
                foreach ($_files as $file) {
                    $this->view->registerCssFile($this->assetUrl . $file);
                }
            }
        }
    }

    /**
     * Publish widget assets and return published url
     * @return string
     */
    private function releaseAssets()
    {
        $assetDir = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'assets';
        $dirs = \Yii::$app->assetManager->publish($assetDir, [
            'forceCopy' => YII_DEBUG
        ]);
        return BaseUrl::base(true) . $dirs[1] .'/';
    }
}